### ISSUE TITLE
automate value pull not working

### ISSUE THREAD

**Issue by MarcoR883** [evercape/hass-resol-KM2#8]
**Describe the bug**
Hi there. I have a Resol DL2 (firmware 2.2.4) and installed this addon. The setup works fine, initially i get the correct vales once. But the values are not updated automatically (the configuration in the device config is 60 seconds). 
When i restart the whole HA instance, the values are also updated once.

**ErrorLog**
in the HA Error log i can see:

Logger: custom_components.resol
Quelle: custom_components/resol/sensor.py:135
Integration: Resol Controller ([Dokumentation](https://github.com/evercape/resol), [Probleme](https://github.com/evercape/resol/issues))
Erstmals aufgetreten: 13:29:52 (332 Vorkommnisse)
Zuletzt protokolliert: 18:29:20

001E66040F1A: Error fetching data from the device: RequestException in fetch_data_km2(): Error while fetching data from 192.168.mylocalIP: Expecting value: line 1 column 1 (char 0) Please log any issues here: https://github.com/evercape/resol/issues

![Screenshot 2024-11-08 183813](https://github.com/user-attachments/assets/3c7351c6-f025-4872-b73f-aa175e364e30)

**Comment by evercape** [comment]
Thanks @MarcoR883 I initially made this integration for the Resol KM2, however, someone tested it on the KM1 and DL2 and said it was working. I dont have a DL2 so if you would kindly provide me access to your DL2 via dyndns.org or a public IP address/port forwarding I will check it out tomorrow and see that I can rectify the issue. I am sure it's not a big problem. Thanks Martin
PS: You can email me on m@evercape.com then you dont need to share your public IP with anyone.

**Comment by evercape** [comment]
Hi @MarcoR883 I have committed the one mistake that I could find (and someone else actually spotted). Here is the updated master: https://github.com/evercape/hass-resol-KM2/commit/c7bef6ba8a3a5f19356bdd9c883bcda187a25a68 Please let me know if it works. Thanks Martin

**Comment by PowerAce-Ronald** [comment]
Hi @evercape Martin,

Here i experience exactly the same problem as @MarcoR883 (using c7bef6b) . Only i'm using different hardware; a Resol MX connected via a vbus/LAN adapter. This adapter seems to be recognized as a DL2 device by HA. After initial setup all sensors with their respective values are created but only updated once. After that the values aren't updated anymore. Nomatter what update interval you set.
<img width="235" alt="{D0BADCE3-519D-457F-883E-B6F35FB04D5A}" src="https://github.com/user-attachments/assets/85d42ae2-a9e5-44a7-86be-3a1d46ed1533">

![afbeelding](https://github.com/user-attachments/assets/c8be1854-275c-4d3b-9325-c29489bb5a75)

To complete the picture the json-live-data-server is running and i see values changing in there (although i have to refresh my browser to see these changing, no clue if that is a similair problem). I have to say the json-live-data-server gives some errors in the log it might be helpful for you:

<img width="691" alt="{705C41DA-D413-4FE1-A0BB-31D706D5581F}" src="https://github.com/user-attachments/assets/89403bba-56f8-4ff8-a20d-55dca77c14a1">



Hope we can fix this together because your integration makes life a lot easier for a lot of people!

Thanks Ronald

**Comment by evercape** [comment]
Hi @PowerAce-Ronald 

I am in email contact with @MarcoR883 and just sent him an update, also pushed it on GitHub.

Can you pls update [sensor.py](https://github.com/evercape/hass-resol-KM2/blob/main/custom_components/resol/sensor.py) and see if this does the trick?

I made a mistake in line 136/138/140 instead of `data=....`.it should read `full_data=..` however don't change anything in line 66/68/70 which look similar. 

I am online for another 30-60minutes let me know how it goes?

Thanks
Martin

**Comment by PowerAce-Ronald** [comment]
Hi @evercape 

I've used the updated sensor.py and reloaded the integration but it didn't solve the problem.

Ronald

**Comment by PowerAce-Ronald** [comment]
Hi @evercape ,

An update after yesterday evening. After our contact and the update of sensor.py i observed the values of the connected sensors for a while and they seemed not to follow the changes shown by the json-live-data-server. These temperature differences were very minor in the range of 0.1 deg (are they filtered?). But maybe i was too early to judge because - coincidence or not - the temperature started to change after midnight...
![{291C0BB2-C923-4D33-BD0B-1E184CC80001}](https://github.com/user-attachments/assets/8893bdf3-0c15-4b3a-a796-d20b2a73f6ee)
Here is a comparison of one sensor connected to resol and anotherone of the builtin sensor of the heatpump boiler. The temperature difference is mostlikely caused by stratification effect since the sensors are not mounted at the same height.
![{799B5168-3B2D-4CC2-8131-EA340398AF76}](https://github.com/user-attachments/assets/d85adaa5-9b1a-4f5b-94a4-a1408d34cb1a)

To me this proves that communication is atleast stable over multiple hours. I will monitor in the following days the behaviour and will also start monitoring other sensors like flow sensor, pump modulation percentage and some other interfaced sensors.

**Comment by evercape** [comment]
Thanks guys for all the help and debugging.

Looks like it works now, someone else on the [forum also confirmed this](https://community.home-assistant.io/t/resol-km2-controller/642184/30).

I will publish a new version with the latest code.

With regards to filtering - when the value is the same, it is not being polled. I did this in order to reduce the data within HA storage. I am not sure about the 0.1 discrepancy, could be due to rounding.

For me to effectively test this, I would need either public IP or dyndns/port forwarding access. Unfortunately, I don't have VBUS or DL2, only KM2.

Again, thanks so much.
Martin

**Comment by MarcoR883** [comment]
Sorry for beeing late,

it works now like a charme with my DL2:

![image](https://github.com/user-attachments/assets/3bbd7cf0-35cc-49f6-8c28-2eff326d2d9a)

Thank you so much!
